### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by zepinglee** [yuxtech/ShiJihuai-complex#1]
1. 数学环境的中正体符号应该使用 `\mathrm`，不应该用 `\textrm`，这不太符合语义。

2. 微分符号“d”应该使用 `\newcommand\dif{\mathop{}\!\mathrm{d}}`，这样跟前面符号的空隙处理得更好。

3. 行内公式使用 display style 主要是因为方正的排版系统功能所限，个人认为应该尽量避免；这里考虑到与原书的一致倒是可以保留，但是会导致一些行间距太小，可以设置
```
\lineskiplimit=2.5pt  % 默认值为 1pt
\lineskip=2.5pt plus .5pt  % 默认值为 0pt
```
对比效果：
<img width="647" alt="Screen Shot 2020-09-30 at 11 18 34" src="https://user-images.githubusercontent.com/12290822/94639558-06e51000-030f-11eb-8c4f-d8c8fe559be1.png">
<img width="639" alt="Screen Shot 2020-09-30 at 11 23 46" src="https://user-images.githubusercontent.com/12290822/94639737-7c50e080-030f-11eb-9bd4-3b7340cd1f83.png">

4. 数学环境中的省略号全部上下居中，这主要是因为 GB/T 3102.11—1993《物理科学和技术中使用的数学符号》按照中文习惯规定的省略号；可以 `\let\mathellipsis\cdots`，然后使用 `\dots`，比如 `1, 2, \dots, n`，这样代码更有通用性；

5. 积分号上下限的位置不是很统一，通常默认上下限是在积分号右侧，如果想要按照国内出版物的习惯也可以用 `amsmath` 的 `intlimits` 选项统一置于上下侧，不必在每处都用 `\int\limits`。`mtpro2` 的文档中说不处理 `amsmath` 的 `intlimits` 选项，但实际有效果。

6. 粗体应该使用 `mtpro2` 提供的 `\mathbold`，这里用的 `\boldsymbol` 并不起作用：
```
设$\boldsymbol s$和$\boldsymbol n$是两个平面向量
```
<img width="742" alt="Screen Shot 2020-09-30 at 12 03 53" src="https://user-images.githubusercontent.com/12290822/94641879-123b3a00-0315-11eb-9044-bc3c7f5538bc.png">

7. 标点符号
```
\catcode`\,=13
\newcommand{,}{，}
\catcode`\。=\active
\newcommand{。}{.}
\catcode`\;=\active
\newcommand{;}{\text{；}}
```
这样设置是有问题的。前文已经设置了开明式标点符号，正文格式的直接用中文的全角符号，数学环境中用西文的符号。
这样将句号直接专为半宽句点会导致结果不符合开明式。
<img width="701" alt="Screen Shot 2020-09-30 at 13 23 16" src="https://user-images.githubusercontent.com/12290822/94647077-4ff28f80-0322-11eb-88ac-3298b824da77.png">

应该用 `xecjk` 的 `Mapping=fullwidth-stop` 将句号“。”转为全宽句点“．”（U+FF0E）。
```
\usepackage{xeCJK}
\defaultCJKfontfeatures{Mapping=fullwidth-stop}
\usepackage[heading,fontset=founder]{ctex}
\setCJKmainfont[BoldFont={FZHei-B01},ItalicFont={FZKai-Z03}]{FZShuSong-Z01}
```
<img width="705" alt="Screen Shot 2020-09-30 at 13 23 22" src="https://user-images.githubusercontent.com/12290822/94647084-53861680-0322-11eb-9774-1fcc823ea4ad.png">

8. 代码风格：(1) 缩进 (2) “=”、“+”、“-” 两侧，“,” 后面一般加空格，这样阅读更加清晰。

9. 二元交集运算符应该用 `\cup` 和 `\cap`，比如 `$A \cup B$`，巨型的交集、并集运算符类似 `\sum`，应该用 `\bigcup` 和 `\bigcap`，不应该用 `\operatorname*{\cup}`。

**Comment by zepinglee** [comment]
另外，PDF 二进制文件不宜放到 repo 里，建议传到 releases 里。 https://github.com/yuxtech/ShiJihuai-complex/releases

**Comment by yuxtech** [comment]
大部分改了，但是有一些我就不改了

**Comment by zepinglee** [comment]
另外欢迎加入 https://github.com/CTeX-org/forum 和 https://t.me/chinesetex 讨论 LaTeX 相关技术。

**Comment by zepinglee** [comment]
补充一些：

1. 常数 e 不应该用 `\mathop{}\!\mathrm{e}`，应该直接用 `\mathrm{e}`。

2. “Schwarz­-Christoffel”中间应该用 en dash `--`。
