### ISSUE TITLE
pdf 版本目录问题

### ISSUE THREAD

**Issue by zhangshenxing** [yuxtech/ShiJihuai-complex#5]
例如3.7如果直接用`一维 $\overline\partial$ 问题的解` 会在pdf目录中显示为 `一维2mu-2mu 问题的解`
可以用 
`一维 \texorpdfstring{$\overline partial$}{∂̅} 问题的解`
 或
`一维 \texorpdfstring{$\overline partial$}{\bar ∂} 问题的解`
来表示pdf目录中出现的章节标题

**Comment by yuxtech** [comment]
你说的那个不是目录，是书签，我把它改一下吧

**Comment by yuxtech** [comment]
> 例如3.7如果直接用`一维 $\overline\partial$ 问题的解` 会在pdf目录中显示为 `一维2mu-2mu 问题的解`
> 可以用
> `一维 \texorpdfstring{$\overline partial$}{∂̅} 问题的解`
> 或
> `一维 \texorpdfstring{$\overline partial$}{\bar ∂} 问题的解`
> 来表示pdf目录中出现的章节标题

才发现原来是我大一数分的助教QAQ
